let state = {}, page = 'dashboard', draft = [], pages = { dashboard: 1, requested: 1, released: 1, catalog: 1, stockHistory: 1, corrections: 1, activity: 1 }, historyQuery = '', historySort = 'date_desc', historyTimer, activityQuery = '', activityType = 'ALL', activityTimer, dashboardQuery = '', dashboardSort = 'level_asc', dashboardTimer, releaseQuery = '', releaseSort = 'date_desc', releaseStart = '', releaseEnd = '', releaseTimer, reportStart = '', reportEnd = '';
const $ = s => document.querySelector(s), esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const date = s => s ? new Date(s).toLocaleString() : '';
function applyTheme(theme) { document.documentElement.dataset.theme=theme;let button=$('#themeToggle');if(button){let dark=theme==='dark';button.querySelector('span').textContent=dark?'☀':'☾';button.setAttribute('aria-label',dark?'Switch to light mode':'Switch to dark mode');button.title=dark?'Switch to light mode':'Switch to dark mode'} }
function toggleTheme() { let next=document.documentElement.dataset.theme==='dark'?'light':'dark';localStorage.setItem('tsi-theme',next);applyTheme(next) }
const label = v => v.is_direct ? v.supply_name : `${v.supply_name} — ${v.variant_name}${v.detail_name ? ' (' + v.detail_name + ')' : ''}`;
function toast(msg, bad = false) { let t = $('#toast'); t.textContent = msg; t.className = bad ? 'error' : ''; t.style.display = 'block'; setTimeout(() => t.style.display = 'none', 3500) }
function openDialog({ title, subtitle = '', body = '', confirmText = 'Save', danger = false, wide = false, onConfirm }) { let m = $('#modal'); $('#modalTitle').textContent = title; $('#modalSubtitle').textContent = subtitle; $('#modalBody').innerHTML = `<div id="modalError" class="modal-error" role="alert"></div>${body}`; let c = $('#modalConfirm'); c.textContent = confirmText; c.className = danger ? 'confirm-danger' : ''; m.querySelector('.modal-card').classList.toggle('wide', wide); m.classList.add('open'); m.setAttribute('aria-hidden', 'false'); document.body.style.overflow = 'hidden'; $('#modalForm').onsubmit = async e => { e.preventDefault(); c.disabled = true; let error = $('#modalError'); error.classList.remove('show'); try { let done = await onConfirm(); if (done !== false) closeDialog() } catch (err) { error.textContent = err.message; error.classList.add('show'); toast(err.message, true) } finally { c.disabled = false } }; setTimeout(() => m.querySelector('input,textarea,select')?.focus(), 50) }
function closeDialog() { let m = $('#modal'); if (!m) return; m.classList.remove('open'); m.setAttribute('aria-hidden', 'true'); if (!$('#drawer')?.classList.contains('open')) document.body.style.overflow = '' }
document.addEventListener('keydown', e => {
  if (e.key !== 'Escape') return
  document.querySelectorAll('.suggestion-menu.open,.supply-picker-menu.open').forEach(menu => menu.classList.remove('open'))
  closeDialog()
})
document.addEventListener('mousedown', e => {
  if (!e.target.closest('.autocomplete')) $('#requestorMenu')?.classList.remove('open')
  if (!e.target.closest('.supply-picker')) $('#supplyPickerMenu')?.classList.remove('open')
})
async function api(path, opt = {}) { let r = await fetch('/api' + path, { headers: { 'Content-Type': 'application/json' }, ...opt }); let d = await r.json(); if (!r.ok || d.error) throw Error(d.error || 'Request failed'); return d }
async function load() { try { state = await api('/state'); render() } catch (e) { toast(e.message, true) } }
const allVariants = () => state.supplies.flatMap(s => s.variants);
function pageItems(items, key, size = 6) { let max = Math.max(1, Math.ceil(items.length / size)); pages[key] = Math.min(Math.max(1, pages[key] || 1), max); return items.slice((pages[key] - 1) * size, pages[key] * size) }
function pagination(key, total, size = 6) { let max = Math.ceil(total / size); if (max <= 1) return ''; let current = pages[key] || 1, start = Math.max(1, current - 2), end = Math.min(max, start + 4); start = Math.max(1, end - 4); let nums = []; for (let i = start; i <= end; i++)nums.push(`<button class="${i === current ? 'active' : ''}" onclick="setPage('${key}',${i})">${i}</button>`); return `<div class="pagination"><span>Page ${current} of ${max}</span><div><button onclick="setPage('${key}',${current - 1})" ${current === 1 ? 'disabled' : ''}>‹</button>${nums.join('')}<button onclick="setPage('${key}',${current + 1})" ${current === max ? 'disabled' : ''}>›</button></div></div>` }
function setPage(key, value) { pages[key] = value; render(); window.scrollTo({ top: 0, behavior: 'smooth' }) }
function toggleNav(open) { document.body.classList.toggle('nav-open', open === undefined ? !document.body.classList.contains('nav-open') : open) }
function go(p) { page = p; draft = []; toggleNav(false); render(); window.scrollTo({ top: 0, behavior: 'smooth' }) }
function render()
{
  const tabs = [['dashboard', '⌂', 'Dashboard', 'Overview of your supply inventory'], ['request', '＋', 'Request', 'Create and manage pending requests'], ['released', '✓', 'Released', 'Release and correction history'], ['activity', '≡', 'Activity Log', 'Complete inventory audit history'], ['reports', 'R', 'Reports', 'View and export inventory reports'], ['configuration', '⚙', 'Configuration', 'Manage supplies and stock'], ['settings', '⋯', 'Settings', 'Backup, restore, and updates']];
  $('#nav').innerHTML = tabs.map(x => `<button class="${page === x[0] ? 'active' : ''}" onclick="go('${x[0]}')"><span class="nav-icon">${x[1]}</span>${x[2]}</button>`).join('');
  const current = tabs.find(x => x[0] === page); $('#pageContext').innerHTML = `<strong>${current[2]}</strong><span>${current[3]}</span>`; document.title = `${current[2]} · Supply Inventory`;
  ({ dashboard, request, requested, released, activity, reports, configuration, settings }[page] || dashboard)();
  applyCurrentPagination();
}
function paginateElements(selector, key, size) { let items = [...document.querySelectorAll(selector)]; if (items.length <= size) return; let max = Math.ceil(items.length / size); pages[key] = Math.min(Math.max(1, pages[key] || 1), max); items.forEach((el, i) => { let visible = i >= (pages[key] - 1) * size && i < pages[key] * size; el.dataset.pageVisible = visible ? 'true' : 'false'; el.style.display = visible ? '' : 'none' }); let host = document.createElement('div'); host.innerHTML = pagination(key, items.length, size); items[items.length - 1].parentElement.append(host.firstElementChild) }
function enhanceCatalogColumns() { let head = $('.catalog-head'); if (head && !head.querySelector('.variants-heading')) { let h = document.createElement('span'); h.className = 'variants-heading'; h.textContent = 'Variants'; head.insertBefore(h, head.children[1]) } document.querySelectorAll('.catalog-row').forEach((row, i) => { let s = state.supplies[i], count = s ? s.variants.filter(v => !v.is_direct).length : 0, label = row.querySelector('.catalog-name small'); if (label) label.textContent = ' Main supply'; let cell = document.createElement('span'); cell.className = 'catalog-variants'; cell.innerHTML = count ? `<b>${count}</b><small>variant${count === 1 ? '' : 's'}</small>` : '<b>—</b><small>none</small>'; row.insertBefore(cell, row.querySelector('.catalog-stat')) }) }
function setHistoryFilter(value) { clearTimeout(historyTimer); historyTimer = setTimeout(() => { historyQuery = value; pages.stockHistory = 1; render(); let input = $('.history-controls input'); input?.focus(); input?.setSelectionRange(value.length, value.length) }, 180) }
function setHistorySort(value) { historySort = value; pages.stockHistory = 1; render() }
function enhanceStockHistory() { let panel = $('.history-panel'), container = $('.stock-history'); if (!panel || !container) return; let head = panel.querySelector('.section-head'); let controls = document.createElement('div'); controls.className = 'history-controls'; controls.innerHTML = `<input value="${esc(historyQuery)}" placeholder="Search supply, variant, or remarks…" oninput="setHistoryFilter(this.value)"><select onchange="setHistorySort(this.value)"><option value="date_desc" ${historySort === 'date_desc' ? 'selected' : ''}>Newest first</option><option value="date_asc" ${historySort === 'date_asc' ? 'selected' : ''}>Oldest first</option><option value="supply_asc" ${historySort === 'supply_asc' ? 'selected' : ''}>Supply A–Z</option><option value="supply_desc" ${historySort === 'supply_desc' ? 'selected' : ''}>Supply Z–A</option><option value="quantity_desc" ${historySort === 'quantity_desc' ? 'selected' : ''}>Quantity: high to low</option><option value="quantity_asc" ${historySort === 'quantity_asc' ? 'selected' : ''}>Quantity: low to high</option></select>`; head.after(controls); let pairs = [...container.querySelectorAll('.stock-history-row')].map((row, i) => ({ row, a: state.recent_additions[i] })); let dir = historySort.endsWith('desc') ? -1 : 1, key = historySort.split('_')[0]; pairs.sort((x, y) => { if (key === 'date') return x.a.created_at.localeCompare(y.a.created_at) * dir; if (key === 'quantity') return (x.a.quantity - y.a.quantity) * dir; return x.a.supply_name.localeCompare(y.a.supply_name) * dir }); let q = historyQuery.trim().toLowerCase(); pairs.forEach(({ row, a }) => { let main = row.querySelector('.stock-history-main'); main.innerHTML = `<b>${esc(a.supply_name)}</b><span class="history-kind">${a.is_direct ? 'Direct stock' : esc(a.variant_name)}</span><small><strong>Remarks:</strong> ${esc(a.remarks || 'No remarks entered')}</small>`; let searchable = `${a.supply_name} ${a.is_direct ? 'direct stock' : a.variant_name} ${a.remarks || ''}`.toLowerCase(); row.classList.toggle('stock-filtered-out', !!q && !searchable.includes(q)); container.append(row) }); if (q && !pairs.some(x => !x.row.classList.contains('stock-filtered-out'))) { let empty = document.createElement('p'); empty.className = 'empty history-no-results'; empty.textContent = 'No stock additions match your search.'; container.append(empty) } }
function applyCurrentPagination() { if (page === 'dashboard') { enhanceDashboardSummaryAndLevels(); enhanceRecentActivities(); paginateElements('.inventory-item:not(.dashboard-filtered-out)', 'dashboard', 5) } if (page === 'request' || page === 'requested') paginateElements('.request-card', 'requested', 5); if (page === 'released') { enhanceReleasedFilters(); paginateElements('.release-card:not(.release-filtered-out)', 'released', 5); paginateElements('.correction-row', 'corrections', 6) } if (page === 'activity') paginateElements('.activity-log-row', 'activity', 10); if (page === 'configuration') { enhanceConfigurationBulk(); enhanceCatalogColumns(); enhanceStockHistory(); enhanceStockWarnings(); paginateElements('.catalog-row', 'catalog', 7); paginateElements('.stock-history-row:not(.stock-filtered-out)', 'stockHistory', 6) } if (page === 'settings') enhanceSettings() }
function totals(vs) { return vs.reduce((a, v) => ({ added: a.added + v.added, used: a.used + v.used, stock: a.stock + v.stock }), { added: 0, used: 0, stock: 0 }) }
function statBlock(t) { let remain = t.added ? Math.max(0, t.stock / t.added * 100) : 0, used = t.added ? Math.max(0, t.used / t.added * 100) : 0; return `<div class="stats"><div class="stat"><span>Remaining</span><b>${t.stock}</b></div><div class="stat"><span>Total added</span><b>${t.added}</b></div><div class="stat"><span>Used</span><b>${t.used}</b></div><div class="stat"><span>Remaining / Used</span><b>${remain.toFixed(0)}% / ${used.toFixed(0)}%</b></div></div><div class="progress"><i style="width:${Math.min(100, remain)}%"></i></div>` }
function setDashboardQuery(value) { clearTimeout(dashboardTimer); dashboardTimer = setTimeout(() => { dashboardQuery = value; pages.dashboard = 1; render(); let input = $('.inventory-controls input'); input?.focus(); input?.setSelectionRange(value.length, value.length) }, 180) }
function setDashboardSort(value) { dashboardSort = value; pages.dashboard = 1; render() }
function enhanceDashboardSummaryAndLevels() { let summaries = state.supplies.map(s => ({ s, t: totals(s.variants) })), available = summaries.filter(x => x.t.stock > 0).length, out = summaries.filter(x => x.t.stock <= 0).length, attention = summaries.filter(x => x.t.added && x.t.stock > 0 && x.t.stock / x.t.added <= .5).length; let grid = $('.summary-grid'); if (grid) grid.innerHTML = `<div class="summary-card"><span class="summary-icon blue">◷</span><div><small>Pending requests</small><b>${state.requested.length}</b></div></div><div class="summary-card"><span class="summary-icon green">✓</span><div><small>Supplies available</small><b>${available}</b></div></div><div class="summary-card"><span class="summary-icon amber">!</span><div><small>Need attention</small><b>${attention}</b></div></div><div class="summary-card"><span class="summary-icon red">×</span><div><small>Out of stock</small><b>${out}</b></div></div>`; let panel=$('.inventory-panel'),head=panel?.querySelector('.section-head'),list=panel?.querySelector('.inventory-list');if(!head||!list)return;let old=head.querySelector('.search');old?.remove();let controls=document.createElement('div');controls.className='inventory-controls';controls.innerHTML=`<input value="${esc(dashboardQuery)}" placeholder="Search supplies…" oninput="setDashboardQuery(this.value)"><select onchange="setDashboardSort(this.value)"><option value="level_asc" ${dashboardSort==='level_asc'?'selected':''}>Lowest stock level first</option><option value="remaining_asc" ${dashboardSort==='remaining_asc'?'selected':''}>Remaining: low to high</option><option value="remaining_desc" ${dashboardSort==='remaining_desc'?'selected':''}>Remaining: high to low</option><option value="name_asc" ${dashboardSort==='name_asc'?'selected':''}>Supply name A–Z</option></select>`;head.append(controls);let rows=[...list.querySelectorAll('.inventory-item')].map((row,i)=>({row,...summaries[i],pct:summaries[i].t.added?summaries[i].t.stock/summaries[i].t.added:0})),q=dashboardQuery.trim().toLowerCase();rows.sort((a,b)=>dashboardSort==='remaining_asc'?a.t.stock-b.t.stock:dashboardSort==='remaining_desc'?b.t.stock-a.t.stock:dashboardSort==='name_asc'?a.s.name.localeCompare(b.s.name):a.pct-b.pct);rows.forEach(x=>{x.row.classList.toggle('dashboard-filtered-out',!!q&&!x.s.name.toLowerCase().includes(q));list.append(x.row)}) }
function dashboard()
{
  let combined = totals(allVariants()), low = state.supplies.filter(s => { let t = totals(s.variants); return t.added && t.stock / t.added <= .2 }).length;
  let supplyRows = state.supplies.map(s => { let t = totals(s.variants), real = s.variants.filter(v => !v.is_direct), pct = t.added ? Math.max(0, t.stock / t.added * 100) : 0, status = pct <= 20 && t.added ? 'low' : pct <= 50 && t.added ? 'medium' : 'good'; return `<div class="inventory-item searchable" data-search="${esc(s.name.toLowerCase())}"><div class="inventory-main"><div class="supply-identity"><span class="supply-icon">${esc(s.name.slice(0, 1).toUpperCase())}</span><div><b>${esc(s.name)}</b><small>${real.length ? real.length + ' variant' + (real.length === 1 ? '' : 's') : 'Direct stock'}</small></div></div><div class="inventory-number"><small>Added</small><b>${t.added}</b></div><div class="inventory-number"><small>Used</small><b>${t.used}</b></div><div class="inventory-number remaining"><small>Remaining</small><b>${t.stock}</b></div><div class="stock-health"><div><span>${pct.toFixed(0)}% remaining</span><em class="stock-label ${status}">${status === 'low' ? 'Low' : status === 'medium' ? 'Watch' : 'In stock'}</em></div><div class="progress"><i class="${status}" style="width:${Math.min(100, pct)}%"></i></div></div></div>${real.length ? `<details class="variant-details"><summary>View variants</summary><div class="variant-list">${real.map(v => { let vp = v.added ? Math.max(0, v.stock / v.added * 100) : 0; return `<div class="variant-row"><div><b>${esc(v.variant_name)}</b>${v.detail_name ? `<small>${esc(v.detail_name)}</small>` : ''}</div><span>${v.added} added</span><span>${v.used} used</span><strong>${v.stock} left</strong><div class="mini-progress"><i style="width:${Math.min(100, vp)}%"></i></div></div>` }).join('')}</div></details>` : ''}</div>` }).join('');
  let recent = [...state.requested.slice(0, 3).map(r => ({ when: r.created_at, text: `Request #${r.id} from ${r.requestor}` })), ...state.released.slice(0, 3).map(r => ({ when: r.released_at, text: `Request #${r.id} released to ${r.requestor}` })), ...state.corrections.slice(0, 3).map(c => ({ when: c.created_at, text: `Returned ${c.quantity} ${c.is_direct ? c.supply_name : c.supply_name + ' — ' + c.variant_name}` }))].sort((a, b) => b.when.localeCompare(a.when)).slice(0, 8);
  $('#app').innerHTML = `<div class="welcome"><div><p class="eyebrow">INVENTORY OVERVIEW</p><h1>Good day, Samboy</h1><p>Here is the current status of your office supplies.</p></div><button onclick="go('request')"><span>+</span> New request</button></div><div class="summary-grid"><div class="summary-card"><span class="summary-icon green">▦</span><div><small>Main supplies</small><b>${state.supplies.length}</b></div></div><div class="summary-card"><span class="summary-icon blue">↓</span><div><small>Total quantity added</small><b>${combined.added}</b></div></div><div class="summary-card"><span class="summary-icon amber">↗</span><div><small>Total quantity used</small><b>${combined.used}</b></div></div><div class="summary-card"><span class="summary-icon red">!</span><div><small>Low-stock supplies</small><b>${low}</b></div></div></div><div class="dashboard-columns"><section class="panel inventory-panel"><div class="section-head"><div><h2>Supply levels</h2><p>Stock across all configured supplies</p></div><input class="search" placeholder="Search supplies…" oninput="filterCards(this.value)"></div><div class="inventory-head"><span>Supply</span><span>Added</span><span>Used</span><span>Remaining</span><span>Stock level</span></div><div class="inventory-list">${supplyRows || '<div class="empty">No supplies yet. Add one in Configuration.</div>'}</div></section><section class="panel activity-panel"><div class="section-head"><div><h2>Recent activity</h2><p>Latest inventory movements</p></div></div><div class="activity-list">${recent.map((x, i) => `<div class="activity-item"><span class="activity-mark ${i === 0 ? 'latest' : ''}"></span><div><b>${esc(x.text)}</b><small>${date(x.when)}</small></div></div>`).join('') || '<p class="empty">No activity yet.</p>'}</div></section></div>`
}
function filterCards(q) { q = q.toLowerCase(); document.querySelectorAll('.searchable').forEach(x => x.style.display = x.dataset.search.includes(q) && x.dataset.pageVisible !== 'false' ? '' : 'none') }
function supplyOptions() { return allVariants().map(v => `<option value="${v.variant_id}">${esc(label(v))} · ${v.stock} available</option>`).join('') }
function request()
{
  let lines = draft.map((x, i) => `<div class="row line"><div><b>${esc(label(x.v))}</b><br><small>${x.v.stock} available</small></div><div><label>Quantity</label><input type="number" min="1" value="${x.quantity}" onchange="draft[${i}].quantity=+this.value"></div><button class="danger" onclick="draft.splice(${i},1);request()">Remove</button></div>`).join('');
  $('#app').innerHTML = `<section class="panel request-panel"><h2>New Request</h2><p class="muted">Choose an existing requestor or enter a new name.</p><form onsubmit="saveRequest(event)"><label>Requestor's name</label><div class="autocomplete"><input id="requestor" required autocomplete="off" placeholder="Type a requestor's name" oninput="showRequestors(this.value)" onfocus="showRequestors(this.value)"><div id="requestorMenu" class="suggestion-menu"></div></div><div class="row"><div><label>Supply item</label><select id="pick"><option value="">Select…</option>${supplyOptions()}</select></div><button type="button" class="secondary" onclick="addLine()">Add item</button></div><div id="draft">${lines || '<p class="empty">Add one or more items.</p>'}</div><div class="actions"><button>Submit request</button></div></form></section>`
}
function showRequestors(value = '') { let menu = $('#requestorMenu'); if (!menu) return; let q = value.trim().toLowerCase(), matches = state.requestors.filter(x => !q || x.name.toLowerCase().includes(q)).slice(0, 8); menu.innerHTML = matches.map((x, i) => `<button type="button" onmousedown="chooseRequestor(${i})"><span>${esc(x.name[0].toUpperCase())}</span>${esc(x.name)}</button>`).join(''); menu._matches = matches; menu.classList.toggle('open', matches.length > 0) }
function chooseRequestor(index) { let menu = $('#requestorMenu'); $('#requestor').value = menu._matches[index].name; menu.classList.remove('open') }
function addLine() { let id = +$('#pick').value, v = allVariants().find(x => x.variant_id === id); if (!v) return toast('Select a supply item.', true); if (draft.some(x => x.v.variant_id === id)) return toast('That item is already in this request.', true); draft.push({ v, quantity: 1 }); request() }
async function saveRequest(e) { e.preventDefault(); try { await api('/requests', { method: 'POST', body: JSON.stringify({ requestor: $('#requestor').value, items: draft.map(x => ({ variant_id: x.v.variant_id, quantity: x.quantity })) }) }); toast('Request saved.'); draft = []; page = 'request'; await load() } catch (e) { toast(e.message, true) } }
function requested() { let itemCount = state.requested.reduce((n, r) => n + r.items.length, 0), body = state.requested.map(r => `<article class="request-card searchable" data-search="${esc((r.requestor + ' ' + r.id).toLowerCase())}"><div class="request-card-head"><div class="request-person"><span>${esc(r.requestor[0].toUpperCase())}</span><div><small>REQUEST #${r.id}</small><h3>${esc(r.requestor)}</h3><time>${date(r.created_at)}</time></div></div><span class="status-badge pending">Awaiting release</span></div><div class="request-lines"><div class="request-line request-line-head"><span>Supply item</span><span>Requested</span><span>Actual release</span></div>${r.items.map(i => `<div class="request-line"><div><b>${esc(i.is_direct ? i.supply_name : i.supply_name + ' — ' + i.variant_name)}</b>${i.detail_name ? `<small>${esc(i.detail_name)}</small>` : ''}</div><strong>${i.requested_qty}</strong><input class="release-${r.id}" data-id="${i.id}" type="number" min="0" value="${i.requested_qty}" aria-label="Actual quantity released"></div>`).join('')}</div><div class="request-card-foot"><span>${r.items.length} item${r.items.length === 1 ? '' : 's'} in this request</span><button onclick="releaseRequest(${r.id})">Review & release →</button></div></article>`).join(''); $('#app').innerHTML = `<div class="page-intro"><div><p class="eyebrow">PENDING WORK</p><h1>Requested supplies</h1><p>Review requested items and record the actual quantities released.</p></div><div class="page-count"><b>${state.requested.length}</b><span>Pending requests</span><small>${itemCount} total line items</small></div></div><div class="list-toolbar"><input class="search" placeholder="Search by requestor or request number…" oninput="filterCards(this.value)"></div><div class="request-list">${body || '<div class="panel empty">No pending requests. New requests will appear here.</div>'}</div>` }
async function releaseRequest(id) { let items = [...document.querySelectorAll('.release-' + id)].map(x => ({ id: +x.dataset.id, quantity: +x.value })), request = state.requested.find(r => r.id === id), variants = new Map(allVariants().map(v => [v.variant_id, v])), total = items.reduce((n, x) => n + x.quantity, 0), review = items.map(item => { let line = request?.items.find(i => i.id === item.id), variant = variants.get(line?.variant_id), available = variant?.stock ?? 0, after = available - item.quantity, name = line ? (line.is_direct ? line.supply_name : line.supply_name + ' — ' + line.variant_name) : 'Supply item'; return `<div class="release-review-row ${after < 0 ? 'insufficient' : ''}"><div><b>${esc(name)}</b>${line?.detail_name ? `<small>${esc(line.detail_name)}</small>` : ''}</div><span><small>Release</small><b>${item.quantity}</b></span><span><small>Available</small><b>${available}</b></span><span><small>After release</small><b>${after}</b></span></div>` }).join(''); openDialog({ title: 'Record this release?', subtitle: 'Review available stock before confirming.', confirmText: 'Record release', wide: true, body: `<div class="release-review">${review}</div><div class="dialog-note dialog-warning"><b>${total} total unit${total === 1 ? '' : 's'}</b>&nbsp; will be deducted from available stock. A negative balance is not allowed.</div>`, onConfirm: async () => { await api('/releases/' + id, { method: 'POST', body: JSON.stringify({ items }) }); toast('Release recorded.'); await load() } }) }
function setReleaseQuery(value) { clearTimeout(releaseTimer); releaseTimer=setTimeout(()=>{releaseQuery=value;pages.released=1;render();let input=$('.release-controls .release-search');input?.focus();input?.setSelectionRange(value.length,value.length)},180) }
function setReleaseOption(field,value) { if(field==='sort')releaseSort=value;if(field==='start')releaseStart=value;if(field==='end')releaseEnd=value;pages.released=1;render() }
function clearReleaseFilters() { releaseQuery='';releaseSort='date_desc';releaseStart='';releaseEnd='';pages.released=1;render() }
function enhanceReleasedFilters() { let toolbar=$('.list-toolbar'),list=$('.release-list');if(!toolbar||!list)return;toolbar.className='release-controls';toolbar.innerHTML=`<div><label>Search</label><input class="release-search" value="${esc(releaseQuery)}" placeholder="Requestor or request number…" oninput="setReleaseQuery(this.value)"></div><div><label>Sort by date</label><select onchange="setReleaseOption('sort',this.value)"><option value="date_desc" ${releaseSort==='date_desc'?'selected':''}>Newest first</option><option value="date_asc" ${releaseSort==='date_asc'?'selected':''}>Oldest first</option></select></div><div><label>Start date</label><input type="date" value="${esc(releaseStart)}" onchange="setReleaseOption('start',this.value)"></div><div><label>End date</label><input type="date" value="${esc(releaseEnd)}" onchange="setReleaseOption('end',this.value)"></div><button class="secondary" onclick="clearReleaseFilters()">Clear</button>`;let pairs=[...list.querySelectorAll('.release-card')].map((row,i)=>({row,r:state.released[i]})),q=releaseQuery.trim().toLowerCase();pairs.sort((a,b)=>a.r.released_at.localeCompare(b.r.released_at)*(releaseSort==='date_desc'?-1:1));let matches=0;pairs.forEach(({row,r})=>{let day=(r.released_at||'').slice(0,10),search=`${r.requestor} ${r.id}`.toLowerCase(),visible=(!q||search.includes(q))&&(!releaseStart||day>=releaseStart)&&(!releaseEnd||day<=releaseEnd);row.classList.toggle('release-filtered-out',!visible);if(visible)matches++;list.append(row)});let count=$('.page-count b');if(count)count.textContent=matches;if(!matches){let empty=document.createElement('p');empty.className='empty release-filter-empty';empty.textContent='No releases match the selected filters.';list.append(empty)} }
function released() { let body = state.released.map(r => `<article class="release-card searchable" data-search="${esc((r.requestor + ' ' + r.id).toLowerCase())}"><div class="request-card-head"><div class="request-person"><span>${esc(r.requestor[0].toUpperCase())}</span><div><small>REQUEST #${r.id}</small><h3>${esc(r.requestor)}</h3><time>Released ${date(r.released_at)}</time></div></div><span class="status-badge complete">Released</span></div><div class="release-lines">${r.items.map(i => `<div class="release-line"><div><b>${esc(i.is_direct ? i.supply_name : i.supply_name + ' — ' + i.variant_name)}</b><small>Requested ${i.requested_qty}</small></div><div class="release-figures"><span><small>Released</small><b>${i.released_qty}</b></span><span><small>Returned</small><b>${i.corrected}</b></span><span><small>Net used</small><b>${i.released_qty - i.corrected}</b></span></div><button class="secondary" ${i.corrected >= i.released_qty ? 'disabled' : ''} onclick="correct(${i.id},${i.released_qty - i.corrected})">Return quantity</button></div>`).join('')}</div></article>`).join(''); let corrections = state.corrections.map(c => `<div class="correction-row"><span class="correction-icon">↩</span><div><b>${c.quantity} returned to ${esc(c.is_direct ? c.supply_name : c.supply_name + ' — ' + c.variant_name)}</b><p>${esc(c.remarks)}</p><small>Request #${c.request_id} · ${esc(c.requestor)} · ${date(c.created_at)}</small></div></div>`).join(''); $('#app').innerHTML = `<div class="page-intro"><div><p class="eyebrow">INVENTORY OUTFLOW</p><h1>Released supplies</h1><p>Review completed releases and correct accidental deductions.</p></div><div class="page-count"><b>${state.released.length}</b><span>Completed releases</span></div></div><div class="list-toolbar"><input class="search" placeholder="Search by requestor or request number…" oninput="filterCards(this.value)"></div><div class="release-list">${body || '<div class="panel empty">No releases have been recorded.</div>'}</div><section class="panel correction-panel"><div class="section-head"><div><h2>Correction history</h2><p>Quantities returned to inventory</p></div><span class="count-chip">${state.corrections.length}</span></div>${corrections || '<p class="empty">No corrections recorded.</p>'}</section>` }
async function correct(id, max) { openDialog({ title: 'Return quantity to stock', subtitle: 'Correct an accidental inventory deduction.', confirmText: 'Record correction', body: `<div class="dialog-note">This correction will not change or delete the original release. You may return up to <b>&nbsp;${max}&nbsp;</b> unit${max === 1 ? '' : 's'}.</div><label>Quantity to return</label><input id="correctionQty" type="number" min="1" max="${max}" required placeholder="Enter quantity"><label>Remarks</label><textarea id="correctionRemarks" rows="3" required placeholder="Explain why this quantity is being returned"></textarea><span class="field-help">Remarks are saved permanently in correction history.</span>`, onConfirm: async () => { await api('/corrections', { method: 'POST', body: JSON.stringify({ item_id: id, quantity: +$('#correctionQty').value, remarks: $('#correctionRemarks').value }) }); toast('Correction recorded and stock returned.'); await load() } }) }
function activityCategory(type) { if (type === 'STOCK_ADDED') return 'ADD'; if (type === 'REQUESTED') return 'REQUEST'; if (type === 'RELEASED') return 'RELEASE'; if (type === 'CORRECTION') return 'MODIFY'; if (type.includes('ARCHIVED')) return 'ARCHIVE'; if (type.includes('RESTORED')) return 'RESTORE'; return type }
function setActivityQuery(value) { clearTimeout(activityTimer); activityTimer = setTimeout(() => { activityQuery = value; pages.activity = 1; render(); let input = $('.activity-toolbar input'); input?.focus(); input?.setSelectionRange(value.length, value.length) }, 180) }
function setActivityType(value) { activityType = value; pages.activity = 1; render() }
function activity() { let q = activityQuery.trim().toLowerCase(), filtered = (state.activities || []).map((a, index) => ({ a, index })).filter(({ a }) => { let category = activityCategory(a.event_type), text = `${a.summary} ${Object.values(a.details || {}).join(' ')}`.toLowerCase(); return (activityType === 'ALL' || category === activityType) && (!q || text.includes(q)) }); let rows = filtered.map(({ a, index }) => { let category = activityCategory(a.event_type); return `<button class="activity-log-row" onclick="openActivityDrawer(${index})"><span class="activity-type ${category.toLowerCase()}">${category}</span><span class="activity-log-summary"><b>${esc(a.summary)}</b><small>${esc(a.entity_type.replaceAll('_', ' '))}</small></span><time>${date(a.created_at)}</time><span class="catalog-arrow">›</span></button>` }).join(''); $('#app').innerHTML = `<div class="page-intro"><div><p class="eyebrow">AUDIT TRAIL</p><h1>Activity log</h1><p>Complete, read-only history of inventory activity.</p></div><div class="page-count"><b>${filtered.length}</b><span>Matching activities</span><small>${state.activities.length} total records</small></div></div><div class="activity-toolbar"><input value="${esc(activityQuery)}" placeholder="Search activity details…" oninput="setActivityQuery(this.value)"><select onchange="setActivityType(this.value)"><option value="ALL" ${activityType === 'ALL' ? 'selected' : ''}>All activity types</option><option value="ADD" ${activityType === 'ADD' ? 'selected' : ''}>Stock added</option><option value="REQUEST" ${activityType === 'REQUEST' ? 'selected' : ''}>Requests</option><option value="RELEASE" ${activityType === 'RELEASE' ? 'selected' : ''}>Releases</option><option value="MODIFY" ${activityType === 'MODIFY' ? 'selected' : ''}>Corrections / modifications</option><option value="ARCHIVE" ${activityType === 'ARCHIVE' ? 'selected' : ''}>Archived</option><option value="RESTORE" ${activityType === 'RESTORE' ? 'selected' : ''}>Restored</option></select></div><section class="panel activity-log"><div class="activity-log-head"><span>Type</span><span>Activity</span><span>Date and time</span><span></span></div><div class="activity-log-list">${rows || '<p class="empty">No activities match the selected filters.</p>'}</div></section>` }
function setReportDate(field, value) { if (field === 'start') reportStart = value; else reportEnd = value }
function clearReportDates() { reportStart = ''; reportEnd = ''; reports() }
function downloadReport(type) { if (reportStart && reportEnd && reportStart > reportEnd) return toast('Start date cannot be after end date.', true); let query = new URLSearchParams({ type }); if (reportStart) query.set('start', reportStart); if (reportEnd) query.set('end', reportEnd); window.location.href = '/api/reports/excel?' + query.toString(); toast('Preparing Excel report…') }
function reports() { let stock = totals(allVariants()), cards = [
  { type:'inventory', mark:'I', title:'Inventory Status', text:'Stock by main supply and variant, including added, released, returned, net used, remaining, and stock status.', note:'Snapshot uses the selected end date' },
  { type:'stock', mark:'S', title:'Stock Additions', text:'Every quantity added to inventory with its supply, variant, remarks, and recorded date.', note:'Uses the selected date range' },
  { type:'requests', mark:'R', title:'Requests and Releases', text:'Requested quantities, actual releases, returns, and net usage for every request line.', note:'Uses the selected date range' },
  { type:'corrections', mark:'C', title:'Correction History', text:'Accidental deductions returned to stock, including requestor, original release, quantity returned, and remarks.', note:'Uses the selected date range' }
]; $('#app').innerHTML = `<div class="page-intro reports-intro"><div><p class="eyebrow">OFFICE REPORTING</p><h1>Reports</h1><p>Review your records and download formatted Excel workbooks.</p></div><button class="report-complete-button" onclick="downloadReport('complete')"><span>↓</span><div><b>Download complete workbook</b><small>Summary and all detailed reports</small></div></button></div><div class="report-summary"><div><small>Stock items</small><b>${allVariants().length}</b></div><div><small>Units remaining</small><b>${stock.stock}</b></div><div><small>Pending requests</small><b>${state.requested.length}</b></div><div><small>Completed releases</small><b>${state.released.length}</b></div></div><section class="panel report-period"><div><h2>Report period</h2><p>Start and end dates filter transactions. Inventory Status and the summary show stock as of the end date.</p></div><label>Start date<input type="date" value="${esc(reportStart)}" onchange="setReportDate('start',this.value)"></label><label>End date<input type="date" value="${esc(reportEnd)}" onchange="setReportDate('end',this.value)"></label><button class="secondary" onclick="clearReportDates()">Clear dates</button></section><div class="report-grid">${cards.map(card => `<article class="panel report-card"><div class="report-card-head"><span>${card.mark}</span><div><h2>${card.title}</h2><small>${card.note}</small></div></div><p>${card.text}</p><div class="report-card-foot"><span>Excel workbook (.xlsx)</span><button onclick="downloadReport('${card.type}')">Download report</button></div></article>`).join('')}</div><section class="report-help"><b>Excel-ready and offline</b><p>Reports are created from the live SQLite database on this computer. Each workbook includes filters, frozen headings, readable column widths, and the date it was generated.</p></section>` }
function configuration()
{
  let sup = state.supplies.map(s => { let t = totals(s.variants), real = s.variants.filter(v => !v.is_direct), pct = t.added ? Math.max(0, t.stock / t.added * 100) : 0; return `<button class="catalog-row searchable" data-search="${esc(s.name.toLowerCase())}" onclick="openSupplyDrawer(${s.id})"><span class="catalog-name"><span class="supply-icon">${esc(s.name[0].toUpperCase())}</span><span><b>${esc(s.name)}</b><small>${real.length ? real.length + ' variant' + (real.length === 1 ? '' : 's') : 'Direct stock'}</small></span></span><span class="catalog-stat"><small>Total added</small><b>${t.added}</b></span><span class="catalog-stat"><small>Used</small><b>${t.used}</b></span><span class="catalog-stat remaining"><small>Remaining</small><b>${t.stock}</b></span><span class="catalog-level"><i><em style="width:${Math.min(100, pct)}%"></em></i><small>${pct.toFixed(0)}%</small></span><span class="catalog-arrow">›</span></button>` }).join('');
  $('#app').innerHTML = `<div class="config-toolbar"><div><p class="eyebrow">SUPPLY MANAGEMENT</p><h1>Stock configuration</h1><p>Select a supply to manage its stock and variants.</p></div><button onclick="openSupplyDialog()">+ Add new supply</button></div><section class="panel config-panel"><div class="config-panel-head"><div><h2>Supply catalog</h2><p>${state.supplies.length} active main suppl${state.supplies.length === 1 ? 'y' : 'ies'}</p></div><input class="search" placeholder="Search catalog…" oninput="filterCards(this.value)"></div><div class="catalog-head"><span>Supply</span><span>Total added</span><span>Used</span><span>Remaining</span><span>Stock level</span><span></span></div><div class="catalog-list">${sup || '<div class="empty">No supplies configured.</div>'}</div></section><section class="panel history-panel"><div class="section-head"><div><h2>Recent stock additions</h2><p>Latest quantities recorded</p></div><span class="count-chip">${state.recent_additions.length}</span></div><div class="stock-history">${state.recent_additions.slice(0, 8).map(a => `<div class="stock-history-row"><span class="stock-add-icon">+</span><div class="stock-history-main"><b>${esc(a.is_direct ? a.supply_name : a.supply_name + ' — ' + a.variant_name)}</b><small>${esc(a.remarks || 'No remarks')}</small></div><strong>+${a.quantity}</strong><time>${date(a.created_at)}</time></div>`).join('') || '<p class="empty">No stock additions.</p>'}</div></section>`
}
function openSupplyDrawer(id) { let s = state.supplies.find(x => x.id === id); if (!s) return; let t = totals(s.variants), direct = s.variants.find(v => v.is_direct), real = s.variants.filter(v => !v.is_direct); $('#drawerContent').innerHTML = `<div class="drawer-head"><div class="drawer-title"><span class="supply-icon">${esc(s.name[0].toUpperCase())}</span><div><small>MAIN SUPPLY</small><h2 id="drawerTitle">${esc(s.name)}</h2></div></div><button class="modal-close" onclick="closeDrawer()">×</button></div><div class="drawer-body"><div class="drawer-totals"><div><small>Total added</small><b>${t.added}</b></div><div><small>Used</small><b>${t.used}</b></div><div><small>Remaining</small><b>${t.stock}</b></div></div>${direct ? `<section class="drawer-section"><div class="drawer-section-head"><div><h3>Direct stock</h3><p>This supply does not use variants.</p></div><div class="drawer-row-actions"><button class="secondary" onclick="openVariantDialog(${s.id})">+ Variant</button><button onclick="openStockDialog(${direct.variant_id})">+ Stock</button></div></div><div class="direct-stock"><span>Available quantity</span><b>${direct.stock}</b></div></section>` : `<section class="drawer-section"><div class="drawer-section-head"><div><h3>Variants</h3><p>${real.length} separately tracked item${real.length === 1 ? '' : 's'}</p></div><button onclick="openVariantDialog(${s.id})">+ Add variant</button></div><div class="drawer-variants">${real.map(v => `<div class="drawer-variant"><div><b>${esc(v.variant_name)}</b><small>${esc(v.detail_name || 'No detailed name')}</small></div><div class="drawer-variant-numbers"><span><small>Added</small>${v.added}</span><span><small>Used</small>${v.used}</span><span><small>Remaining</small>${v.stock}</span></div><div class="drawer-row-actions"><button onclick="openStockDialog(${v.variant_id})">+ Stock</button><button class="danger" onclick="archiveVariant(${v.variant_id})">Archive</button></div></div>`).join('') || '<div class="empty">No active variants.</div>'}</div></section>`}<section class="drawer-danger"><div><h3>Archive supply</h3><p>Hide this supply from active inventory while retaining its complete history.</p></div><button class="danger" onclick="archiveSupply(${s.id})">Archive supply</button></section></div>`; let d = $('#drawer'); d.classList.add('open'); d.setAttribute('aria-hidden', 'false'); document.body.style.overflow = 'hidden' }
function closeDrawer() { let d = $('#drawer'); if (!d) return; d.classList.remove('open'); d.setAttribute('aria-hidden', 'true'); if (!$('#modal').classList.contains('open')) document.body.style.overflow = '' }
function archiveSupply(id) { let supply = state.supplies.find(s => s.id === id); openDialog({ title: 'Archive this supply?', subtitle: supply?.name || '', confirmText: 'Archive supply', danger: true, body: '<div class="dialog-note dialog-warning">The supply will disappear from the dashboard, catalog, and new requests. All stock, release, and correction history will remain safely stored.</div>', onConfirm: async () => { await api('/archive/supply', { method: 'POST', body: JSON.stringify({ supply_id: id }) }); closeDrawer(); toast('Supply archived.'); await load() } }) }
function archiveVariant(id) { let parent = state.supplies.find(s => s.variants.some(v => v.variant_id === id)), variant = parent?.variants.find(v => v.variant_id === id); openDialog({ title: 'Archive this variant?', subtitle: variant?.variant_name || '', confirmText: 'Archive variant', danger: true, body: '<div class="dialog-note dialog-warning">The variant will be hidden from active inventory and new requests. Its complete transaction history will remain stored.</div>', onConfirm: async () => { await api('/archive/variant', { method: 'POST', body: JSON.stringify({ variant_id: id }) }); toast('Variant archived.'); await load(); if (parent) openSupplyDrawer(parent.id); else closeDrawer() } }) }
function openSupplyDialog() { openDialog({ title: 'Add a new supply', subtitle: 'Create direct stock or separate variants.', confirmText: 'Create supply', wide: true, body: `<label>Main supply name</label><input id="sname" required placeholder="e.g. Bond Paper"><label class="check-label"><input id="hasvariants" style="width:auto" type="checkbox" onchange="$('#directFields').style.display=this.checked?'none':'block';$('#variantbox').style.display=this.checked?'block':'none'"> This supply has variants</label><div id="directFields"><label>Starting quantity</label><input id="sqty" type="number" min="0" value="0"></div><div id="variantbox" style="display:none"><div class="dialog-note">Each variant keeps its own quantity. Detailed names are optional.</div><div id="variantrows"></div><button type="button" class="secondary" style="margin-top:10px" onclick="variantRow()">+ Add variant row</button></div>`, onConfirm: async () => { let has = $('#hasvariants').checked, variants = [...document.querySelectorAll('.variantrow')].map(r => ({ name: r.querySelector('.vname').value, detail_name: r.querySelector('.vdetail').value, quantity: +r.querySelector('.vqty').value })); if (has && !variants.length) { toast('Add at least one variant row.', true); return false } await api('/supplies', { method: 'POST', body: JSON.stringify({ name: $('#sname').value, quantity: +($('#sqty')?.value || 0), variants: has ? variants : [] }) }); toast('Supply created.'); await load() } }) }
function variantRow() { let d = document.createElement('div'); d.className = 'modal-variant-row variantrow'; d.innerHTML = '<input class="vname" placeholder="Variant name" required><input class="vdetail" placeholder="Detailed name (optional)"><input class="vqty" type="number" min="0" value="0" placeholder="Quantity"><button type="button" class="danger" onclick="this.parentElement.remove()">×</button>'; $('#variantrows').append(d) }
function openStockDialog(id) { let v = allVariants().find(x => x.variant_id === id), parentId = v?.supply_id; openDialog({ title: 'Add stock', subtitle: label(v), confirmText: 'Add to inventory', body: `<div class="dialog-note">Current quantity: <b>&nbsp;${v.stock}</b>. This addition will be recorded in dated history.</div><label>Quantity to add</label><input id="stockQty" type="number" min="1" required placeholder="Enter quantity"><label>Remarks <span class="muted">(optional)</span></label><textarea id="stockRemarks" rows="2" placeholder="e.g. September delivery"></textarea>`, onConfirm: async () => { await api('/stock', { method: 'POST', body: JSON.stringify({ variant_id: id, quantity: +$('#stockQty').value, remarks: $('#stockRemarks').value }) }); toast('Stock addition recorded.'); await load(); if ($('#drawer').classList.contains('open')) openSupplyDrawer(parentId) } }) }
function openVariantDialog(id) { let s = state.supplies.find(x => x.id === id); openDialog({ title: 'Add a variant', subtitle: s.name, confirmText: 'Add variant', body: `<label>Variant name</label><input id="variantName" required placeholder="e.g. A4"><label>Detailed name <span class="muted">(optional)</span></label><input id="variantDetail" placeholder="e.g. PaperOne 80gsm"><div class="dialog-note dialog-warning" style="margin-top:14px">A supply with direct stock history cannot be converted to variants. This protects existing inventory records.</div>`, onConfirm: async () => { await api('/variants', { method: 'POST', body: JSON.stringify({ supply_id: id, name: $('#variantName').value, detail_name: $('#variantDetail').value }) }); toast('Variant added.'); await load(); if ($('#drawer').classList.contains('open')) openSupplyDrawer(id) } }) }
function settings() { $('#app').innerHTML = `<section class="panel"><h2>Settings</h2><p><b>Installed version:</b> ${esc(state.version)}</p><p id="update"><button onclick="checkUpdate()">Check for updates</button> <span class="muted">Internet is only used for this check.</span></p></section><section class="panel"><h2>Backup & Restore</h2><p>Backups are stored beside the database, outside the application folder.</p><button onclick="backup()">Create database backup</button><label>Restore from backup</label><div class="row"><select id="backupfile"><option value="">Choose a backup…</option>${state.backups.map(x => `<option>${esc(x)}</option>`).join('')}</select><button class="danger" onclick="restore()">Restore</button></div><p><small>Restoring replaces current records. A safety copy of the current database is created first.</small></p></section>` }
async function backup() { try { let d = await api('/backup', { method: 'POST', body: '{}' }); toast('Backup created: ' + d.file); await load() } catch (e) { toast(e.message, true) } }
async function restore() { let f = $('#backupfile').value; if (!f) return toast('Choose a backup.', true); openDialog({ title: 'Restore database?', subtitle: f, confirmText: 'Restore database', danger: true, body: `<div class="dialog-note dialog-warning">Restoring replaces the current inventory records. A safety copy of the current database will be created automatically.</div><label>Type RESTORE to confirm</label><input id="restoreConfirm" required autocomplete="off" placeholder="RESTORE">`, onConfirm: async () => { let d = await api('/restore', { method: 'POST', body: JSON.stringify({ file: f, confirm: $('#restoreConfirm').value }) }); toast('Database restored. Safety copy: ' + d.safety_copy); await load() } }) }
async function checkUpdate() { let el = $('#update'); el.textContent = 'Checking…'; try { let d = await api('/update'); if (!d.configured) el.textContent = d.message; else if (d.offline) el.textContent = d.message; else if (d.available) el.innerHTML = `<b>Version ${esc(d.latest)} is available.</b> <a class="button" target="_blank" rel="noopener" href="${esc(d.url)}">Open release page</a>`; else el.textContent = `You are up to date (version ${state.version}).` } catch (e) { el.textContent = 'Could not check for updates. The app remains usable offline.' } }
function enhanceStockWarnings() { document.querySelectorAll('.catalog-row').forEach((row, i) => { let s = state.supplies[i]; if (!s) return; let t = totals(s.variants), pct = t.added ? t.stock / t.added * 100 : 0, level = t.stock === 0 ? 'critical' : pct <= 20 ? 'critical' : pct <= 50 ? 'warning' : 'healthy'; row.querySelector('.catalog-stat.remaining')?.classList.add(level); row.querySelector('.catalog-level')?.classList.add(level) }) }
function enhanceConfigurationBulk() { let toolbar=$('.config-toolbar'),primary=toolbar?.querySelector('button');if(!toolbar||!primary||$('#bulkSupplyButton'))return;let actions=document.createElement('div');actions.className='config-toolbar-actions';actions.innerHTML='<button id="bulkSupplyButton" class="secondary" onclick="openBulkSupplyDialog()">Bulk add supplies</button>';actions.append(primary);toolbar.append(actions) }
function openBulkSupplyDialog() { openDialog({ title:'Bulk add supplies', subtitle:'Paste multiple supplies and variants in one operation.', confirmText:'Import supplies', wide:true, body:`<div class="dialog-note">Use one row per direct supply or variant, separated by the <b>&nbsp;|&nbsp;</b> character.<br><b>Supply | Variant | Detailed name | Starting quantity</b></div><label>Supply rows</label><textarea id="bulkSupplyRows" rows="10" required placeholder="Ballpen | | | 50&#10;Bond Paper | Short | PaperOne 80gsm | 20&#10;Bond Paper | Long | | 20&#10;Ink | Black | | 10"></textarea><span class="field-help">For a supply without variants, leave Variant and Detailed name blank. Supplies that already exist are rejected. The entire import is cancelled if any row is invalid.</span>`, onConfirm:async()=>{let lines=$('#bulkSupplyRows').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),entries=lines.map((line,i)=>{let parts=line.split('|').map(x=>x.trim());if(parts.length!==4)throw Error(`Row ${i+1}: use exactly four columns separated by |`);let quantity=Number(parts[3]);if(!Number.isInteger(quantity)||quantity<0)throw Error(`Row ${i+1}: quantity must be a whole number of zero or more.`);return {supply:parts[0],variant:parts[1],detail_name:parts[2],quantity}});let d=await api('/supplies/bulk',{method:'POST',body:JSON.stringify({entries})});toast(`${d.created} supplies imported successfully.`);await load()}}) }
function enhanceSettings() { let panels = document.querySelectorAll('.panel'), p = panels[1]?.querySelector('p'); if (p) p.innerHTML = `Backups are saved in the visible folder: <b>${esc(state.backup_dir || 'backups')}</b>`; if ($('#resetPanel')) return; let section = document.createElement('section'); section.id = 'resetPanel'; section.className = 'panel reset-panel'; section.innerHTML = `<div><h2>Reset current database</h2><p>Remove every supply, request, release, correction, and activity from the live database. A safety backup is created automatically before reset.</p></div><button class="danger" onclick="resetCurrentDatabase()">Reset database</button>`; $('#app').append(section) }
function resetCurrentDatabase() { openDialog({ title: 'Reset the current database?', subtitle: 'This removes all live inventory records.', confirmText: 'Reset database', danger: true, body: `<div class="dialog-note dialog-warning">A safety backup will be created in <b>&nbsp;${esc(state.backup_dir || 'backups')}&nbsp;</b> before the database is cleared.</div><label>Type RESET DATABASE to confirm</label><input id="resetConfirm" required autocomplete="off" placeholder="RESET DATABASE"><span class="field-help">This action cannot be undone without restoring the safety backup.</span>`, onConfirm: async () => { let d = await api('/reset', { method: 'POST', body: JSON.stringify({ confirm: $('#resetConfirm').value }) }); toast('Database reset. Safety backup: ' + d.safety_backup); await load() } }) }
const baseRequest = request;
request = function () { baseRequest(); let form = $('#app').innerHTML; requested(); let temp = document.createElement('div'); temp.innerHTML = $('#app').innerHTML; let toolbar = temp.querySelector('.list-toolbar'), list = temp.querySelector('.request-list'), count = state.requested.length; $('#app').innerHTML = `${form}<section class="combined-pending"><div class="combined-head"><div><h2>Pending requests</h2><p>Review and release requests without leaving this page.</p></div><span class="count-chip">${count}</span></div>${toolbar?.outerHTML || ''}${list?.outerHTML || ''}</section>`; enhanceSupplyPicker() }
function enhanceSupplyPicker() { let select=$('#pick');if(!select)return;let wrap=document.createElement('div');wrap.className='supply-picker';wrap.innerHTML=`<input id="supplySearch" autocomplete="off" placeholder="Search or choose a supply item" onfocus="showSupplyPicker(this.value)" oninput="showSupplyPicker(this.value)"><input id="pick" type="hidden"><button type="button" class="picker-toggle secondary" onclick="showSupplyPicker($('#supplySearch').value,true)">⌄</button><div id="supplyPickerMenu" class="supply-picker-menu"></div>`;select.replaceWith(wrap) }
function showSupplyPicker(value='',force=false) { let menu=$('#supplyPickerMenu');if(!menu)return;if(force&&menu.classList.contains('open')){menu.classList.remove('open');return}let q=value.trim().toLowerCase(),items=allVariants().filter(v=>force||!q||label(v).toLowerCase().includes(q));menu.innerHTML=items.map(v=>`<button type="button" onmousedown="chooseSupplyItem(${v.variant_id})"><span><b>${esc(label(v))}</b><small>${v.stock} available</small></span></button>`).join('')||'<p>No matching supply items.</p>';menu.classList.add('open') }
function chooseSupplyItem(id) { let v=allVariants().find(x=>x.variant_id===id);$('#pick').value=id;$('#supplySearch').value=label(v);$('#supplyPickerMenu').classList.remove('open') }
const baseOpenSupplyDrawer = openSupplyDrawer;
openSupplyDrawer = function (id) { baseOpenSupplyDrawer(id); let s = state.supplies.find(x => x.id === id); if (!s) return; let active = s.variants.filter(v => !v.is_direct), cards = [...document.querySelectorAll('.drawer-variant')]; active.forEach((v, i) => { let button = cards[i]?.querySelector('button.danger'); if (button && v.stock !== 0) { button.disabled = true; button.title = `${v.stock} remaining — fully use this variant before archiving`; button.textContent = 'Stock remains' } }); let supplyButton = $('.drawer-danger button'); let total = totals(s.variants); if (supplyButton && total.stock !== 0) { supplyButton.disabled = true; supplyButton.title = `${total.stock} remaining — fully use this supply before archiving`; supplyButton.textContent = 'Stock remains' } let archived = s.archived_variants || []; if (archived.length) { let section = document.createElement('section'); section.className = 'drawer-section archived-section'; section.innerHTML = `<div class="drawer-section-head"><div><h3>Archived variants</h3><p>${archived.length} hidden item${archived.length === 1 ? '' : 's'} available to restore</p></div></div><div class="drawer-variants">${archived.map(v => `<div class="drawer-variant archived"><div><b>${esc(v.variant_name)}</b><small>${esc(v.detail_name || 'No detailed name')}</small></div><div class="drawer-variant-numbers"><span><small>Added</small>${v.added}</span><span><small>Used</small>${v.used}</span><span><small>Remaining</small>${v.stock}</span></div><button onclick="restoreVariant(${v.variant_id},${id})">Restore variant</button></div>`).join('')}</div>`; $('.drawer-danger').before(section) } }
function restoreVariant(variantId, supplyId) { let s = state.supplies.find(x => x.id === supplyId), v = s?.archived_variants?.find(x => x.variant_id === variantId); openDialog({ title: 'Restore this variant?', subtitle: v?.variant_name || '', confirmText: 'Restore variant', body: '<div class="dialog-note">The variant will return to active inventory and can be selected in new requests.</div>', onConfirm: async () => { await api('/restore/variant', { method: 'POST', body: JSON.stringify({ variant_id: variantId }) }); toast('Variant restored.'); await load(); openSupplyDrawer(supplyId) } }) }
function enhanceRecentActivities() { let list = $('.activity-list'); if (!list || !state.activities) return; list.innerHTML = state.activities.slice(0, 5).map((a, i) => `<button class="activity-item" onclick="openActivityDrawer(${i})"><span class="activity-mark ${i === 0 ? 'latest' : ''}"></span><span><b>${esc(a.summary)}</b><small>${date(a.created_at)}</small></span><em>›</em></button>`).join('') || '<p class="empty">No activity yet.</p>'; if (state.activities.length > 5) list.insertAdjacentHTML('beforeend','<button class="view-all-activity" onclick="go(\'activity\')">View complete activity log →</button>') }
function openActivityDrawer(index) { let a = state.activities[index]; if (!a) return; let details = Object.entries(a.details || {}).map(([k, v]) => `<div class="activity-detail-row"><small>${esc(k)}</small><b>${esc(v)}</b></div>`).join(''); $('#drawerContent').innerHTML = `<div class="drawer-head"><div class="drawer-title"><span class="activity-large-icon">${a.event_type.includes('ARCHIVED') ? '⌫' : a.event_type.includes('RESTORED') ? '↻' : a.event_type === 'CORRECTION' ? '↩' : '↗'}</span><div><small>ACTIVITY DETAILS</small><h2 id="drawerTitle">${esc(a.summary)}</h2></div></div><button class="modal-close" onclick="closeDrawer()">×</button></div><div class="drawer-body"><div class="activity-time"><small>Date and time</small><b>${date(a.created_at)}</b></div><section class="drawer-section"><div class="drawer-section-head"><div><h3>Details</h3><p>Recorded inventory information</p></div></div><div class="activity-details">${details || '<p class="empty">No additional details.</p>'}</div></section><div class="dialog-note">This activity is part of the inventory audit history and is kept for reference.</div></div>`; let d = $('#drawer'); d.classList.add('open'); d.setAttribute('aria-hidden', 'false'); document.body.style.overflow = 'hidden' }
applyTheme(localStorage.getItem('tsi-theme')||'light');
load();
